language: node_js
node_js: stable

os: linux

cache:
    yarn: true

install:
    - yarn install # npm ci
script:
    - yarn docs:build
deploy:
    provider: pages
    cleanup: false
    local_dir: vuepress
    token: $GITHUB_TOKEN
    keep_history: true
    on:
        branch: master
