language: node_js
node_js: stable

install:
  - yarn install # npm ci
script:
  - yarn docs:build
deploy:
  provider: pages
  cleanup: true
  local_dir: vuepress
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
